# Generated by Django 5.1.7 on 2025-04-14 09:28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("peoples", "0002_customuser_groups_customuser_user_permissions"),
    ]

    operations = [
        migrations.AlterField(
            model_name="designation",
            name="level",
            field=models.IntegerField(default=0),
        ),
    ]
