# Generated by Django 5.1.7 on 2025-04-14 09:42

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("peoples", "0003_alter_designation_level"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="user_type",
            field=models.CharField(
                choices=[("Employee", "Employee"), ("Client", "Client")], max_length=10
            ),
        ),
    ]
