# Generated by Django 5.1.7 on 2025-04-14 12:27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("peoples", "0004_alter_customuser_user_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="employee",
            name="emp_id",
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
