# Generated by Django 5.1.7 on 2025-04-14 12:32

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("peoples", "0005_employee_emp_id"),
    ]

    operations = [
        migrations.RenameField(
            model_name="employee",
            old_name="emp_id",
            new_name="employee_id",
        ),
    ]
