# Generated by Django 5.1.7 on 2025-04-15 09:01

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("peoples", "0006_rename_emp_id_employee_employee_id"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="employee",
            name="employee_id",
        ),
    ]
