# Generated by Django 5.1.7 on 2025-04-15 09:03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("peoples", "0007_remove_employee_employee_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="employee",
            name="employee_id",
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
