# Generated by Django 5.1.7 on 2025-04-15 09:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("peoples", "0012_employee_employee_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="employee",
            name="employee_id",
            field=models.CharField(blank=True, max_length=15, unique=True),
        ),
    ]
