# Generated by Django 5.1.7 on 2025-04-15 10:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("peoples", "0013_alter_employee_employee_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="team",
            name="note",
            field=models.TextField(blank=True, null=True),
        ),
    ]
