# Generated by Django 5.1.7 on 2025-05-04 06:08

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("peoples", "0014_alter_team_note"),
    ]

    operations = [
        migrations.DeleteModel(
            name="EmployeeAddress",
        ),
    ]
