# Generated by Django 5.1.7 on 2025-05-16 12:26

import cloudinary.models
import cloudinary_storage.storage
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("peoples", "0016_employeecurrentaddress_employeepermanentaddress"),
    ]

    operations = [
        migrations.AlterField(
            model_name="employeedocuments",
            name="aadhar_card",
            field=models.FileField(
                blank=True,
                null=True,
                storage=cloudinary_storage.storage.RawMediaCloudinaryStorage(),
                upload_to="employee/documents/aadhar_card/",
            ),
        ),
        migrations.AlterField(
            model_name="employeedocuments",
            name="higher_education_certificate",
            field=models.FileField(
                blank=True,
                null=True,
                storage=cloudinary_storage.storage.RawMediaCloudinaryStorage(),
                upload_to="employee/documents/higher_education_certificate/",
            ),
        ),
        migrations.AlterField(
            model_name="employeedocuments",
            name="pan_card",
            field=models.FileField(
                blank=True,
                null=True,
                storage=cloudinary_storage.storage.RawMediaCloudinaryStorage(),
                upload_to="employee/documents/pan_card/",
            ),
        ),
        migrations.AlterField(
            model_name="employeedocuments",
            name="photo",
            field=cloudinary.models.CloudinaryField(
                blank=True, max_length=255, null=True, verbose_name="image"
            ),
        ),
        migrations.AlterField(
            model_name="employeedocuments",
            name="resume",
            field=models.FileField(
                blank=True,
                null=True,
                storage=cloudinary_storage.storage.RawMediaCloudinaryStorage(),
                upload_to="employee/documents/resume/",
            ),
        ),
    ]
