# Generated by Django 5.1.7 on 2025-05-16 12:48

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("peoples", "0017_alter_employeedocuments_aadhar_card_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="employeedocuments",
            name="photo",
            field=models.ImageField(
                blank=True, null=True, upload_to="employee/documents/photo/"
            ),
        ),
    ]
