# Generated by Django 5.1.7 on 2025-05-17 09:56

import cloudinary_storage.storage
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("peoples", "0018_alter_employeedocuments_photo"),
    ]

    operations = [
        migrations.AddField(
            model_name="meeting",
            name="meeting_members",
            field=models.ManyToManyField(
                related_name="meeting_members", to="peoples.employee"
            ),
        ),
        migrations.AlterField(
            model_name="employeedocuments",
            name="photo",
            field=models.ImageField(
                blank=True,
                null=True,
                storage=cloudinary_storage.storage.MediaCloudinaryStorage(),
                upload_to="employee/documents/photo/",
            ),
        ),
    ]
