# Generated by Django 5.1.7 on 2025-05-20 05:02

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("peoples", "0019_meeting_meeting_members_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="meeting",
            name="scheduled_by",
        ),
    ]
