# Generated by Django 5.1.7 on 2025-05-20 05:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("peoples", "0020_remove_meeting_scheduled_by"),
    ]

    operations = [
        migrations.AddField(
            model_name="meeting",
            name="scheduled_by",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="scheduled_by",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
