# Generated by Django 5.1.7 on 2025-05-20 06:38

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="proposals",
            name="valid_until",
        ),
        migrations.AddField(
            model_name="proposals",
            name="status",
            field=models.CharField(
                choices=[
                    ("Discussing", "Discussing"),
                    ("Accept", "Accept"),
                    ("Reject", "Reject"),
                ],
                default="Discussing",
                max_length=15,
            ),
            preserve_default=False,
        ),
    ]
